server:
  port: 8761
#  servlet:
#    context-path: /server1
eureka:
  instance:
    hostname: server1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/
spring:
  application:
    name: eurekaServer1
#  sleuth:
#    sampler:
#      rate: 1
