server:
  port: 8762
eureka:
  instance:
    hostname: server2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/
spring:
  application:
    name: eurekaServer2